# Site
title: Pipoca Cafeinada
subtitle:
description: Um blog sobre um desenvolvedor fascinado demais com jogos e Web, arte e pipoca com caf√©
keywords: 
author: Jhow
language: pt
timezone: America/Sao_Paulo

# URL
url: https://pipocacafeinada.com.br
repo: https://github.com/jonathan-santos/pipocacafeinada
root: /
permalink: :lang/:title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang

# Writing
new_post_name: :lang/:title.md
default_layout: post
titlecase: false
external_link:
  enable: true
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  
# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: DD/MM/YYYY
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Extensions
theme: hexo-jhow-theme
theme_config:
  noFaq: false
  primaryColor: '#ff2d9a'
  secondaryColor: '#8be9fd'
